import React, { useEffect, useState, createContext, useContext, Component } from 'react';
type Language = 'es' | 'en';
type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    hotels: 'Hotels',
    strategies: 'Strategies',
    prices: 'Prices',
    performance: 'Performance',
    market: 'Market & Analysis',
    // Dashboard
    executive_pricing_panel: 'Executive Pricing Intelligence Panel',
    pricing_intelligence_system: 'Pricing Intelligence System:',
    active: 'Active',
    last_update: 'Last update: 5 minutes ago',
    more_revenue: 'More Revenue',
    vs_manual_pricing: 'vs. Manual Pricing',
    price_precision: 'Price Precision',
    excellent: 'Excellent',
    automatic_adjustments: 'Automatic Adjustments',
    today: 'Today',
    revenue_performance: 'Revenue Performance (30 days)',
    competitive_position: 'Competitive Position',
    market_position: 'Market Position',
    premium_position: 'Premium Position',
    premium_position_desc: 'Your hotel is positioned in the premium segment of the local market',
    recent_automatic_actions: 'Recent Automatic Actions',
    last_auto_adjustments: 'Latest adjustments made by the automation system',
    view_all_actions: 'View all actions',
    our_hotel: 'Our Hotel',
    competition: 'Competition',
    competition_average: 'Competition (Average)',
    target: 'Target',
    loading_chart_data: 'Loading chart data...',
    loading_radar: 'Loading radar chart...',
    loading_position: 'Loading position indicator...',
    total_revenue: 'Total Revenue',
    vs_previous_month: 'vs previous month',
    average_daily_rate: 'Average Daily Rate',
    vs_competition: 'vs competition',
    average_occupancy: 'Average Occupancy',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    // Hotels Page
    competitive_intelligence: 'Hotel Competitive Intelligence',
    monitoring_competitors: 'Monitoring competitors within a 10km radius',
    create_alert: 'Create Alert',
    export: 'Export',
    table: 'Table',
    map: 'Map',
    loading_competitor_map: 'Loading competitor map...',
    no_competitors_match: 'No competitors match the selected criteria',
    no_competitors_found: 'No competitors found',
    adjust_filters_or_radius: 'Try adjusting filters or expanding the search radius',
    update_data: 'Update Data',
    // Hotel Filters
    filters_and_search: 'Filters and Competitor Search',
    active_filters: 'Active filters',
    clear_all: 'Clear all',
    clear: 'Clear',
    search_competitor_hotels: 'Search competitor hotels...',
    distance: 'Distance',
    price: 'Price',
    price_range: 'Price Range',
    above: 'Above',
    rating: 'Rating',
    stars: 'Stars',
    very_good: 'Very Good',
    good: 'Good',
    less_than: 'Less than',
    amenities: 'Amenities',
    amenity: 'Amenity',
    wifi: 'WiFi',
    gym: 'Gym',
    pool: 'Pool',
    restaurant: 'Restaurant',
    parking: 'Parking',
    pets: 'Pets',
    business_center: 'Business Center',
    room_service: 'Room Service',
    spa: 'Spa',
    bar: 'Bar',
    // Strategies Page
    optimization_strategies: 'Optimization Strategies',
    create_new_rule: 'Create New Rule',
    current_strategy: 'Current Strategy',
    elasticity_score: 'Elasticity Score',
    roi_strategy: 'ROI Strategy',
    market_volatility: 'Market Volatility',
    low_risk: 'Low',
    medium_risk: 'Medium',
    high_risk: 'High',
    risk_evaluation: 'Risk Evaluation',
    risk_medium: 'Medium Risk',
    safety_limits: 'Safety Limits',
    edit_global_limits: 'Edit Global Limits',
    minimum_allowed_price: 'Minimum Allowed Price:',
    maximum_allowed_price: 'Maximum Allowed Price:',
    safe: 'Safe',
    limit: 'Limit',
    priority_system: 'Priority System',
    high_priority: 'High',
    medium_priority: 'Medium',
    low_priority: 'Low',
    critical_safety_rules: 'Critical safety rules',
    revenue_optimization: 'Revenue optimization',
    seasonal_adjustments: 'Seasonal adjustments',
    applies_first: 'Applies first',
    priority_conflict_rule: 'If there are conflicts between rules of the same level, the most recent one prevails.',
    // What-If Simulator
    what_if_simulator: 'What-If Simulator',
    rate_adjustment: 'Rate Adjustment',
    revenue_impact: 'Revenue Impact',
    occupancy_change: 'Occupancy Change',
    new_revpar: 'New RevPAR',
    // Prices Page
    real_time_prices: 'Real-Time Prices',
    base_rate: 'Base Rate',
    event_premium: 'Event Premium',
    competitor_avg_price: 'Competitor Avg Price',
    price_variance: 'Price Variance',
    demand_forecast_7d: 'Demand Forecast 7d',
    demand_forecast_30d: 'Demand Forecast 30d',
    price_demand_elasticity: 'Price-Demand Elasticity',
    revenue_impact_metric: 'Revenue Impact',
    price_trend: 'Price Trend: Us vs Competitors',
    events_calendar_impact: 'Events Calendar & Impact',
    market_price_distribution: 'Market Price Distribution',
    // Performance Page
    performance_analysis: 'Performance Analysis',
    detailed_metrics: 'Detailed metrics on system accuracy and performance',
    revenue_growth_mom: 'Revenue Growth MoM',
    adr_performance: 'ADR Performance',
    revpar_trend: 'RevPAR Trend',
    market_share_evolution: 'Market Share Evolution',
    competitive_index: 'Competitive Index:',
    optimization_score: 'Optimization Score:',
    precision_analysis: 'Precision Analysis',
    last_week: 'Last week',
    precision: 'precision',
    predicted: 'Predicted:',
    actual: 'Actual:',
    variation: 'Variation:',
    analysis_factors: 'Analysis Factors',
    performance_metrics: 'Performance Metrics',
    prediction_accuracy: 'Prediction Accuracy',
    confidence_level: 'Confidence Level',
    absolute_error: 'Absolute Error',
    last_two_weeks: 'Last 2 weeks',
    loading_analysis_data: 'Loading analysis data...',
    // Time Range Filter
    two_weeks: '2 weeks',
    last_month: 'Last month',
    custom: 'Custom',
    // Market Analysis Page
    market_analysis: 'Market & Analysis',
    updated_ago: 'Updated',
    min_ago: 'min ago',
    filters: 'Filters',
    market_size: 'Market Size',
    market_growth: 'Market Growth',
    concentration_hhi: 'Concentration (HHI)',
    competitor_movements: 'Competitor Movements',
    // Market Analysis Components
    market_trends: 'Market Trends',
    market_trends_tooltip: 'Analysis of key market trends during the selected period',
    price_trend_vs_competition: 'Price: Hotel vs Competition',
    occupancy_trend_vs_competition: 'Occupancy: Hotel vs Competition',
    revpar_trend_vs_competition: 'RevPAR: Hotel vs Competition',
    competitive_ranking: 'Competitive Ranking',
    competitive_ranking_tooltip: 'Ranking of competitors based on key metrics',
    ranking: 'Ranking',
    establishment: 'Establishment',
    pricing: 'Pricing',
    occupancy: 'Occupancy',
    satisfaction: 'Satisfaction',
    market_share: 'Market Share',
    adjustment: 'Adjustment',
    suggested_adjustment: 'Suggested Adjustment',
    our_hotel_label: 'OUR HOTEL',
    competitor_b: 'Hotel Competitor B',
    competitor_c: 'Hotel Competitor C',
    last_7_days: 'Last 7 days',
    last_30_days: 'Last 30 days',
    // Settings
    appearance: 'Appearance',
    language: 'Language',
    dark_mode: 'Dark Mode',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    account: 'Account',
    edit_profile: 'Edit profile',
    change_password: 'Change password',
    account_preferences: 'Account preferences',
    security: 'Security',
    notifications: 'Notifications',
    email_notifications: 'Email notifications',
    push_notifications: 'Push notifications',
    two_factor_auth: 'Two-factor authentication',
    // Help Panel
    faq: 'FAQ',
    support: 'Support',
    keyboard_shortcuts: 'Keyboard shortcuts',
    faq_competition_question: 'How to interpret competition analysis?',
    faq_competition_answer: 'Competition analysis shows price, occupancy and reputation comparisons of competing hotels in your area. Use this data to adjust your pricing strategies.',
    faq_data_update_question: 'How often is data updated?',
    faq_data_update_answer: 'Data is updated in real-time for critical metrics like prices and availability. Market analysis metrics are updated every 4 hours.',
    faq_rules_question: 'How to create automatic pricing rules?',
    faq_rules_answer: "Go to the Strategies section, click 'Create New Rule' and follow the wizard to set up conditions and automatic actions.",
    email_contact: 'Email contact',
    support_phone: 'Support phone',
    live_chat: 'Live chat',
    start_live_chat: 'Start live chat',
    service_available: 'Service available',
    shortcut: 'Shortcut',
    action: 'Action',
    open_global_search: 'Open global search',
    close_dialogs: 'Close dialogs and panels',
    open_bookmarks: 'Open bookmarks panel',
    open_help_center: 'Open help center',
    toggle_theme: 'Toggle light/dark theme',
    // Error messages
    loading_error: 'Error loading data',
    loading_risk: 'Loading risk indicator...'
  },
  es: {
    // Navigation
    dashboard: 'Resumen',
    hotels: 'Hoteles',
    strategies: 'Estrategias',
    prices: 'Precios',
    performance: 'Rendimiento',
    market: 'Mercado & Análisis',
    // Dashboard
    executive_pricing_panel: 'Panel Ejecutivo de Inteligencia de Tarifas',
    pricing_intelligence_system: 'Sistema de Inteligencia de Tarifas:',
    active: 'Activo',
    last_update: 'Última actualización: hace 5 minutos',
    more_revenue: 'Más Ingresos',
    vs_manual_pricing: 'vs. Precios Manuales',
    price_precision: 'Precisión de Precios',
    excellent: 'Excelente',
    automatic_adjustments: 'Ajustes Automáticos',
    today: 'Hoy',
    revenue_performance: 'Rendimiento de Ingresos (30 días)',
    competitive_position: 'Posición Competitiva',
    market_position: 'Posición en el Mercado',
    premium_position: 'Posición Premium',
    premium_position_desc: 'Tu hotel está posicionado en el segmento premium del mercado local',
    recent_automatic_actions: 'Acciones Automáticas Recientes',
    last_auto_adjustments: 'Últimos ajustes realizados por el sistema de automatización',
    view_all_actions: 'Ver todas las acciones',
    our_hotel: 'Nuestro Hotel',
    competition: 'Competencia',
    competition_average: 'Competencia (Promedio)',
    target: 'Objetivo',
    loading_chart_data: 'Cargando datos del gráfico...',
    loading_radar: 'Cargando gráfico de radar...',
    loading_position: 'Cargando indicador de posición...',
    total_revenue: 'Ingresos Totales',
    vs_previous_month: 'vs mes anterior',
    average_daily_rate: 'TDP Promedio',
    vs_competition: 'vs competencia',
    average_occupancy: 'Ocupación Promedio',
    low: 'Bajo',
    medium: 'Medio',
    high: 'Alto',
    // Hotels Page
    competitive_intelligence: 'Inteligencia Competitiva de Hoteles',
    monitoring_competitors: 'Monitoreo de competidores en un radio de 10km',
    create_alert: 'Crear Alerta',
    export: 'Exportar',
    table: 'Tabla',
    map: 'Mapa',
    loading_competitor_map: 'Cargando mapa de competidores...',
    no_competitors_match: 'No hay competidores que coincidan con los criterios seleccionados',
    no_competitors_found: 'No se encontraron competidores',
    adjust_filters_or_radius: 'Intenta ajustar los filtros de búsqueda o ampliar el radio',
    update_data: 'Actualizar Datos',
    // Hotel Filters
    filters_and_search: 'Filtros y Búsqueda de Competidores',
    active_filters: 'Filtros activos',
    clear_all: 'Limpiar todos',
    clear: 'Limpiar',
    search_competitor_hotels: 'Buscar hoteles competidores...',
    distance: 'Distancia',
    price: 'Precio',
    price_range: 'Rango de Precio',
    above: 'Más de',
    rating: 'Puntuación',
    stars: 'Estrellas',
    very_good: 'Muy Bueno',
    good: 'Bueno',
    less_than: 'Menos de',
    amenities: 'Servicios',
    amenity: 'Servicio',
    wifi: 'WiFi',
    gym: 'Gimnasio',
    pool: 'Piscina',
    restaurant: 'Restaurante',
    parking: 'Estacionamiento',
    pets: 'Mascotas',
    business_center: 'Centro de Negocios',
    room_service: 'Servicio a Habitaciones',
    spa: 'Spa',
    bar: 'Bar',
    // Strategies Page
    optimization_strategies: 'Estrategias de Optimización',
    create_new_rule: 'Crear Nueva Regla',
    current_strategy: 'Estrategia Actual',
    elasticity_score: 'Score Elasticidad',
    roi_strategy: 'ROI Estrategia',
    market_volatility: 'Volatilidad del Mercado',
    low_risk: 'Bajo',
    medium_risk: 'Medio',
    high_risk: 'Alto',
    risk_evaluation: 'Evaluación de Riesgo',
    risk_medium: 'Riesgo Medio',
    safety_limits: 'Límites de Seguridad',
    edit_global_limits: 'Editar Límites Globales',
    minimum_allowed_price: 'Precio Mínimo Permitido:',
    maximum_allowed_price: 'Precio Máximo Permitido:',
    safe: 'Seguro',
    limit: 'Límite',
    priority_system: 'Sistema de Prioridades',
    high_priority: 'Alta',
    medium_priority: 'Media',
    low_priority: 'Baja',
    critical_safety_rules: 'Reglas críticas de seguridad',
    revenue_optimization: 'Optimización de ingresos',
    seasonal_adjustments: 'Ajustes estacionales',
    applies_first: 'Se aplica primero',
    priority_conflict_rule: 'Si hay conflictos entre reglas del mismo nivel, prevalece la más reciente.',
    // What-If Simulator
    what_if_simulator: 'Simulador What-If',
    rate_adjustment: 'Ajuste de Tarifa',
    revenue_impact: 'Impacto en Ingresos',
    occupancy_change: 'Cambio en Ocupación',
    new_revpar: 'Nuevo RevPAR',
    // Prices Page
    real_time_prices: 'Precios en Tiempo Real',
    base_rate: 'Tarifa Base',
    event_premium: 'Prima por Eventos',
    competitor_avg_price: 'Precio Promedio Competencia',
    price_variance: 'Varianza de Precios',
    demand_forecast_7d: 'Pronóstico Demanda 7d',
    demand_forecast_30d: 'Pronóstico Demanda 30d',
    price_demand_elasticity: 'Elasticidad Precio-Demanda',
    revenue_impact_metric: 'Impacto en Ingresos',
    price_trend: 'Tendencia de Precios: Nosotros vs Competidores',
    events_calendar_impact: 'Calendario de Eventos e Impacto',
    market_price_distribution: 'Distribución de Precios en el Mercado',
    // Performance Page
    performance_analysis: 'Análisis de Rendimiento',
    detailed_metrics: 'Métricas detalladas sobre precisión y desempeño del sistema',
    revenue_growth_mom: 'Crecimiento de Ingresos MoM',
    adr_performance: 'ADR Performance',
    revpar_trend: 'Tendencia RevPAR',
    market_share_evolution: 'Evolución Cuota de Mercado',
    competitive_index: 'Índice Competitivo:',
    optimization_score: 'Puntuación Optimización:',
    precision_analysis: 'Análisis de Precisión',
    last_week: 'Última semana',
    precision: 'precisión',
    predicted: 'Predicho:',
    actual: 'Real:',
    variation: 'Variación:',
    analysis_factors: 'Factores de Análisis',
    performance_metrics: 'Métricas de Performance',
    prediction_accuracy: 'Precisión de Predicción',
    confidence_level: 'Nivel de Confianza',
    absolute_error: 'Error Absoluto',
    last_two_weeks: 'Últimas 2 semanas',
    loading_analysis_data: 'Cargando datos de análisis...',
    // Time Range Filter
    two_weeks: '2 semanas',
    last_month: 'Último mes',
    custom: 'Personalizado',
    // Market Analysis Page
    market_analysis: 'Mercado & Análisis',
    updated_ago: 'Actualizado hace',
    min_ago: 'min',
    filters: 'Filtros',
    market_size: 'Tamaño del Mercado',
    market_growth: 'Crecimiento del Mercado',
    concentration_hhi: 'Concentración (HHI)',
    competitor_movements: 'Movimientos Competidores',
    // Market Analysis Components
    market_trends: 'Tendencias de Mercado',
    market_trends_tooltip: 'Análisis de tendencias clave del mercado en el periodo seleccionado',
    price_trend_vs_competition: 'Precio: Hotel vs Competencia',
    occupancy_trend_vs_competition: 'Ocupación: Hotel vs Competencia',
    revpar_trend_vs_competition: 'RevPAR: Hotel vs Competencia',
    competitive_ranking: 'Ranking Competitivo',
    competitive_ranking_tooltip: 'Clasificación de competidores basada en métricas clave',
    ranking: 'Ranking',
    establishment: 'Establecimiento',
    pricing: 'Pricing',
    occupancy: 'Ocupa',
    satisfaction: 'Satisfacción',
    market_share: 'Market Share',
    adjustment: 'Ajuste',
    suggested_adjustment: 'Ajuste Sugerido',
    our_hotel_label: 'NUESTRO',
    competitor_b: 'Hotel Competidor B',
    competitor_c: 'Hotel Competidor C',
    last_7_days: 'Últimos 7 días',
    last_30_days: 'Últimos 30 días',
    // Settings
    appearance: 'Apariencia',
    language: 'Idioma',
    dark_mode: 'Modo oscuro',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    account: 'Cuenta',
    edit_profile: 'Editar perfil',
    change_password: 'Cambiar contraseña',
    account_preferences: 'Preferencias de cuenta',
    security: 'Seguridad',
    notifications: 'Notificaciones',
    email_notifications: 'Notificaciones por email',
    push_notifications: 'Notificaciones push',
    two_factor_auth: 'Autenticación de dos factores',
    // Help Panel
    faq: 'FAQ',
    support: 'Soporte',
    keyboard_shortcuts: 'Atajos de teclado',
    faq_competition_question: '¿Cómo interpretar el análisis de competencia?',
    faq_competition_answer: 'El análisis de competencia muestra comparativas de precios, ocupación y reputación de hoteles competidores en tu área. Utiliza estos datos para ajustar tus estrategias de precios.',
    faq_data_update_question: '¿Con qué frecuencia se actualizan los datos?',
    faq_data_update_answer: 'Los datos se actualizan en tiempo real para las métricas críticas como precios y disponibilidad. Las métricas de análisis de mercado se actualizan cada 4 horas.',
    faq_rules_question: '¿Cómo crear reglas automáticas de precios?',
    faq_rules_answer: "Dirígete a la sección de Estrategias, haz clic en 'Crear Nueva Regla' y sigue el asistente para configurar condiciones y acciones automáticas.",
    email_contact: 'Contacto por correo',
    support_phone: 'Teléfono de soporte',
    live_chat: 'Chat en vivo',
    start_live_chat: 'Iniciar chat en vivo',
    service_available: 'Servicio disponible',
    shortcut: 'Atajo',
    action: 'Acción',
    open_global_search: 'Abrir búsqueda global',
    close_dialogs: 'Cerrar diálogos y paneles',
    open_bookmarks: 'Abrir panel de guardados',
    open_help_center: 'Abrir centro de ayuda',
    toggle_theme: 'Cambiar tema claro/oscuro',
    // Error messages
    loading_error: 'Error al cargar los datos',
    loading_risk: 'Cargando indicador de riesgo...'
  }
};
const LanguageContext = createContext<LanguageContextType>({
  language: 'es',
  setLanguage: () => {},
  t: (key: string) => key
});
export const useLanguage = () => useContext(LanguageContext);
export const LanguageProvider: React.FC<{
  children: React.ReactNode;
}> = ({
  children
}) => {
  // Initialize with stored language or default to Spanish
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage === 'en' || savedLanguage === 'es' ? savedLanguage : 'es';
  });
  // Set language and save to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };
  // Translation function
  const t = (key: string) => {
    return translations[language][key] || key;
  };
  // Save language preference when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);
  return <LanguageContext.Provider value={{
    language,
    setLanguage,
    t
  }}>
      {children}
    </LanguageContext.Provider>;
};